/*
 * Copyright 2026 CodeMatters, Lda.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

syntax = "proto3";

package spine.client;

import "spine/options.proto";

option (type_url_prefix) = "type.spine.io";
option java_package = "io.spine.client.grpc";
option java_multiple_files = true;
option java_outer_classname = "SubscriptionServiceProto";

import "spine/client/subscription.proto";
import "spine/core/response.proto";

// A service for subscribing to receive updates by a specified topic.
//
// The subscription topic defines a type in updates of which the client code is interested, and
// filtering conditions (e.g. by values of fields or identity).
//
// Creating a subscription consists of two steps:
//  * Step 1: creating a `Subscription` instance. This step verifies that the type specified in
//    the `Topic` is available at the server, and prepares backend structures for delivering
//    updates. Subscription is created by the `Subscribe(Topic)` call.
//    together with the contexts of the events.
//
//  * Step 2: activating the subscription. This step turns the subscription on.
//    Activation is performed by the `Activate(Subscription)` call.
//
// The client will receive updates until the subscription is cancelled via `Cancel(Subscription)`.
//
service SubscriptionService {

    // Creates the subscription to the particular read-side updates.
    //
    // Topic defines the target of subscription.
    //
    // NOTE: this method only creates a `Subscription` for the passed `Topic`.
    // To start listening for updates, please call `Activate(Subscription)`.
    //
    rpc Subscribe(Topic) returns (Subscription);

    // Activates the subscription.
    //
    // The client will start receiving the updates when 1) an instance of the type specified
    // in the topic changes and 2) filtering conditions are met. See `spine.client.Target`.
    //
    // Cancelled subscriptions cannot be activated. Passing a cancelled subscription will result
    // in a run-time error.
    //
    rpc Activate(Subscription) returns (stream SubscriptionUpdate);

    // Cancels the given subscription.
    //
    // Clients will stop receiving the `SubscriptionUpdate` after this method is called.
    //
    // The subscription is destroyed as the result of this call. To restore the subscription,
    // please call `Subscribe(Topic)` and then `Activate(Subscription)` again.
    //
    rpc Cancel(Subscription) returns (core.Response);
}
